In [2]:
# 14 paskaita # Failų nuskaitymas ir įrašymas

x = [1,2,3,4,5]
new_x = [skaicius -0.75 for skaicius in x]
print(new_x)

[0.25, 1.25, 2.25, 3.25, 4.25]


In [3]:
import numpy as np

In [6]:
# array
x = np.arange(0, 10, 2)
print(x)
print(type(x))

[0 2 4 6 8]
<class 'numpy.ndarray'>


In [7]:
y = x - 0.75
print(y)

[-0.75  1.25  3.25  5.25  7.25]


In [ ]:
np.average()
np.min()
np.mean()
np.median()

In [8]:
a_list = [i for i in range(1, 11)]
print(a_list)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [9]:
a_array = np.asarray(a_list)
print(a_array + 0.75)

[ 1.75  2.75  3.75  4.75  5.75  6.75  7.75  8.75  9.75 10.75]


In [11]:
x = [1,2,3]
y = [1,4,5]
x_np = np.asarray(x)
y_np = np.asarray(y)
c = x_np * y_np
print(c)


[ 1  8 15]


In [13]:
np.min(x)
np.max(y_np)

5

In [19]:
atsitiktinis = np.random.randint(0, 10, 100)  # cia butina nurodyti ribas tarp kuriu generuoja
print(atsitiktinis)

[3 7 3 8 8 5 8 3 1 1 5 6 9 0 6 2 4 1 2 8 0 2 0 0 1 2 9 0 3 6 2 6 8 9 0 1 9
 1 1 3 2 6 8 5 8 5 4 4 3 1 3 8 2 3 3 5 0 3 1 0 5 2 8 5 2 1 7 3 1 4 3 3 8 9
 7 7 6 4 9 4 2 1 6 5 8 1 0 1 8 4 5 0 4 0 8 0 1 1 2 9]


In [21]:
atsitiktinis_float = np.random.rand(100)  # 0-1
print(atsitiktinis_float)

[0.79872962 0.95811176 0.77883551 0.51521999 0.83800103 0.92624316
 0.06300589 0.29036514 0.51353143 0.83114375 0.83672625 0.84504516
 0.36626761 0.23036892 0.73846936 0.94034695 0.58351475 0.28327818
 0.88471587 0.806667   0.84280424 0.80290034 0.37172783 0.33431142
 0.41550728 0.18158281 0.03551586 0.28281839 0.35493513 0.23566624
 0.29960535 0.55024484 0.38298353 0.10877031 0.27767685 0.55221344
 0.36936375 0.1984478  0.29178475 0.43280916 0.33407939 0.02190825
 0.99102451 0.36530872 0.25309527 0.92739288 0.47884843 0.4876494
 0.8961195  0.2738529  0.05507891 0.90325057 0.79080933 0.52838543
 0.90818316 0.54127235 0.68807871 0.6032856  0.35248057 0.33452393
 0.20097207 0.26306737 0.57812195 0.78171629 0.95680367 0.76452249
 0.90872666 0.22756192 0.88438097 0.85652174 0.41424634 0.02841676
 0.04710532 0.84025122 0.01064966 0.69461606 0.3560652  0.84788763
 0.89083531 0.5260562  0.37538688 0.08227951 0.15692309 0.46853129
 0.07106491 0.39187587 0.10415612 0.97922039 0.52609069 0.69399

In [26]:
xas = np.random.randint(1, 10, 100)
svoriai = np.random.rand(100)
# mean in average
vidurkis = np.mean(xas)
print(vidurkis)
sv_vid = np.average(xas, weights=svoriai)
print(sv_vid)
# median()
medx = np.median(xas)
print(medx, np.min(xas), np.max(xas))

4.95
4.805470483801657
5.0 1 9


In [33]:
l = np.linspace(0, 10, 15)
print(l)

[ 0.          0.71428571  1.42857143  2.14285714  2.85714286  3.57142857
  4.28571429  5.          5.71428571  6.42857143  7.14285714  7.85714286
  8.57142857  9.28571429 10.        ]


In [36]:
# asarray , arange, min, mix, mean, average, median
n_np = np.arange(0, 10)
# kaip metodai:
minn = n_np.min()
print(minn)
print(n_np.mean())
print(n_np.max())


0
4.5
9


In [71]:
%load_ext autoreload

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [72]:
%autoreload 2

In [73]:
import modulis 

In [74]:
print(modulis.A)

70


In [75]:
modulis.printA()

As esu nauja printA() funkcija
Dar vienas pakeitimas


In [77]:
# iškelkite savo anksčiau rašytas Vehicle, Car, etc klases į modulį
# ir patikrinkite klasių veikimą
# sukurdami kintamuosius ir patikrindami jų veikimą

test = modulis.Car(P= 'pavadinimas', R=5000, S= 4)
print(test.GetSeats())

test = modulis.Bus (P= 'pavadinimas', R=5000, S= 4)
print(test.GetSeats())

test = modulis.Train(P= 'pavadinimas', R=5000, S= 4)
print(test.GetSeats()) 



pavadinimas turi 4 sedimu vietu
pavadinimasturi 4 sedimu vietu 
pavadinimasturi 4 sedimu vietu


In [97]:
#sukurkite failus nuskaitančią klasę, ji turi būti aprašyta jūsų kuriamame modulyje;
#ta klasė turi nuskaityti pateiktą failą, ir suskaidyti stulpelius į sąrašus:
#sąrašai I, U, j, P, duomenys iš juos iš atitinkamų taip pat pavadintų stulpelių
#realizuokite tai, jog klasė rastų tokį dydį - maksimalų P, suskaičiuotų tokį dydį pce = Pmax / 1000 * 100%;
#šie dydžiai turi būti pasiekiamį arba kaip atributas, arba galite įdėti metodą jam gauti

# from modulis import FailoNuskaitymas
# tekstas = FailoNuskaitymas ("REF_D_1k_FW_2.05.dat")
# tekstas.readFile()
# print(tekstas.getPCE())


In [2]:
#sukurkite failus nuskaitančią klasę, ji turi būti aprašyta jūsų kuriamame modulyje;
#ta klasė turi nuskaityti pateiktą failą, ir suskaidyti stulpelius į sąrašus:
#sąrašai I, U, j, P, duomenys iš juos iš atitinkamų taip pat pavadintų stulpelių
#realizuokite tai, jog klasė rastų tokį dydį - maksimalų P, suskaičiuotų tokį dydį pce = Pmax / 1000 * 100%;
#šie dydžiai turi būti pasiekiamį arba kaip atributas, arba galite įdėti metodą jam gauti


import modulis 


kintamasis = modulis.Txtreader("REF_D_1k_FW_2.05.dat") 
kintamasis.skaitytojas()
kintamasis.getPmax()
kintamasis.getPCE()


2.4974205000000005

In [ ]:
# Rasos sprendimas su privaciomis 11 ir 32 eilutemis. (sintakses pazimejimas __)

class keturiolika_failu():
    def __init__(self, Pavadinimas, Skirtukas):
        self.Pavadinimas = Pavadinimas
        self.Skirtukas = Skirtukas
        self.I = []
        self.U = []
        self.j = []
        self.p = []
        self.__dataReader() # kreipiasi i dataReader; __ padar privaciu ir naudojami tik klases viduje
    def __dataReader(self):
        fname = self.Pavadinimas
        file = open(fname, mode='r', encoding= 'utf-8')
        sarasas = file.readlines()
        file.close()
        for eilute in sarasas[1::]:
            self.I.append(float(eilute.split(self.Skirtukas)[0]))
            self.U.append(float(eilute.split(self.Skirtukas)[1]))           
            self.j.append(float(eilute.split(self.Skirtukas)[2]))
            self.p.append(float(eilute.split(self.Skirtukas)[3].replace('\n', '')))
    def getPmax(self):
        Pmax = (max(self.p))
        return Pmax
    
    def getPCE(self):
        Pmax= self.getPmax()
        PCE = round((Pmax / 1000 * 100),2)
        return PCE
    
sarasas = keturiolika_failu('REF_D_5k_FW_2.03.dat',';')
# sarasas.__dataReader()
print(sarasas.getPCE())

In [5]:
import pandas as pd

In [4]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
  Using cached pandas-2.2.1-cp312-cp312-win_amd64.whl.metadata (19 kB)
   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   ---------------------------------------- 0.1/11.5 MB 1.7 MB/s eta 0:00:07
   - -------------------------------------- 0.5/11.5 MB 6.3 MB/s eta 0:00:02
   ---- ----------------------------------- 1.3/11.5 MB 10.4 MB/s eta 0:00:01
   ------- -------------------------------- 2.2/11.5 MB 12.8 MB/s eta 0:00:01
   ---------- ----------------------------- 3.1/11.5 MB 14.4 MB/s eta 0:00:01
   -------------- ------------------------- 4.1/11.5 MB 15.6 MB/s eta 0:00:01
   ----------------- ---------------------- 5.1/11.5 MB 16.2 MB/s eta 0:00:01
   -------------------- ------------------- 6.0/11.5 MB 16.7 MB/s eta 0:00:01
   ------------------------ --------------- 7.0/11.5 MB 17.3 MB/s eta 0:00:01
   --------------------------- ------------ 8.0/11.5 MB 17.7 MB/s eta 0:00:01
   

In [6]:
pip install matplotlib

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [7]:
import pandas as pd

In [8]:
import matplotlib.pyplot as plt